Event.create({:title => "Calvin Harris, Live at MSG", :venue => "Madison Square Garden", :address => "4 Pennsylvania Plaza, New York, NY 10001", :imgurl => "http://www.nh-hotels.it/offer/concerts-italy/concerts-italy.jpg", :description => "Able to contain and even channel the pulsing sphere of energy that exudes from a forceful EDM drop with his chrome Doctor Octopus arms, Calvin Harris is truly the Chuck Norris of our generation.", :date => "04/14", :time => "11:00 PM"})

Event.create({:title => "KA Sigma Chapter, Spring Formal", :venue => "Tybee Gardens", :address => "20 14th Street Tybee Island, GA 31328", :imgurl => "http://i1123.photobucket.com/albums/l543/hercampusphoto/Places/Other%20places/250e16cb.jpg", :description => "Honor the traditions and values of the antebellum American south at this year's Kappa Alpha Order, Sigma Chapter spring formal! Invitation only.", :date => "11/30", :time => "7:00 PM"})

Event.create({:title => "Carolina Cup Steeplechase", :venue => "Springdale Race Course", :address => "200 Knights Hill Road, Camden, South Carolina",:imgurl => "http://www.aepiunc.org/wp-content/uploads/216732_10151423906737615_770169408_n.jpg", :description => "It has many names, perhaps the most illustrious being \"Frat Mecca.\" Carolina Cup is where keg stands, fried chicken, floppy hats and drunk college kids are at their best.", :date => "12/11", :time => "2:00 PM"})

Event.create({:title => "Pool Party", :venue => "Davidson College Athletic Center", :address => "Davidson College, Davidson, NC", :imgurl => "http://www.bathsbudapest.com/wp-content/uploads/2013/04/Szechenyi-Bath-Party-Budapest-Szecska-Sandor-Fegyverneky.jpg", :description => "Yeah, things are going to get wet. Clothing optional.", :date => "07/21", :time => "9:50 PM"})

Event.create({:title => "Youth Soccer Tournament", :venue => "Richardson Stadium", :address => "Davidson College, Davidson, NC", :imgurl => "http://ryanaweaver.com/files/2013/02/kids-soccer-game.jpg", :description => "The annual Davison College youth soccer torunament is back for another round. Grab a lawn chair, a cooler of beer, and get ready to watch some tykes kick a ball. Plenty of fun for the whole family.", :date => "09/15", :time => "8:00 PM"})

Event.create({:title => "Dev Bootcamp Hackathon", :venue => "Dev Bootcamp Office", :address => "633 Folsom Street, San Francisco, CA", :imgurl => "http://www.thedrum.com/uploads/drum_column_article/119859/main_images/hackathon_0.jpg", :description => "The greatest and original coding bootcamp is hosting a hackathon! Come prove your skills and drink beer with us.", :date => "07/21", :time => "8:00 AM"})

Event.create({:title => "SF Giants vs. Oakland Athletics", :venue => "AT&T Park", :address => "24 Willie Mays Plaza, San Francisco, CA 94107", :imgurl => "http://www2.pictures.zimbio.com/gi/Coco+Crisp+Oakland+Athletics+v+San+Francisco+dkOj3C-S295l.jpg", :description => "It's true: baseball is boring. So come for the hotdogs and beer!", :date => "06/29", :time => "6:00 PM"})

Event.create({:title => "Google I/O Conference", :venue => "Moscone Center", :address => "747 Howard Street, San Francisco, CA 94103", :imgurl => "http://d2omthbq56rzfx.cloudfront.net/wp-content/uploads/2011/05/MacBook-Pro-users-at-Google-IO-2011-image-004.jpg", :description => "Google I/O features highly technical, in-depth sessions focused on building web, mobile, and enterprise applications with Google and open web technologies.", :date => "07/30", :time => "12:00 PM"})

Event.create({:title => "Michael Brun, Live at Ruby Skye", :venue => "Ruby Skye", :address => "420 Mason St, San Francisco, CA 94102", :imgurl => "http://partylegacies.com/wp-content/uploads/2013/09/Michael-Brun.jpg", :description => "Working alongside the likes of Calvin Harris, Avicii and Dirty South, up-and-coming Michael Brun is quickly building a reputation as one of the best DJs stateside", :date => "08/04", :time => "9:00 PM"})

Event.create({:title => "San Jose Sharks vs. LA Kings", :venue => "SAP Center at San Jose", :address => "525 W Santa Clara St, San Jose, CA 95113", :imgurl => "http://blogimages.thescore.com/nhl/files/2013/05/dustin-brown.jpg", :description => "Pacific Division rivals face off in round 1 of the 2014 Stanley Cup Playoffs. Can Jonathan Quick continue to perform at the Olympic level, or will the Kings come crashing down?", :date => "05/25", :time => "4:00 PM"})