Event.create({:title => "Calvin Harris, Live at MSG", :venue => "Madison Square Garden", :address => "4 Pennsylvania Plaza, New York, NY 10001", :imgurl => "http://www.nh-hotels.it/offer/concerts-italy/concerts-italy.jpg", :description => "Able to contain and even channel the pulsing sphere of energy that exudes from a forceful EDM drop with his chrome Doctor Octopus arms, Calvin Harris is truly the Chuck Norris of our generation.", :date => "04/14", :time => "11:00 PM"})

Event.create({:title => "KA Sigma Chapter, Spring Formal", :venue => "Tybee Gardens", :address => "20 14th Street Tybee Island, GA 31328", :imgurl => "http://i1123.photobucket.com/albums/l543/hercampusphoto/Places/Other%20places/250e16cb.jpg", :description => "Honor the traditions and values of the antebellum American south at this year's Kappa Alpha Order, Sigma Chapter spring formal! Invitation only.", :date => "11/30", :time => "7:00 PM"})

Event.create({:title => "Carolina Cup Steeplechase", :venue => "Springdale Race Course", :address => "200 Knights Hill Road, Camden, South Carolina",:imgurl => "http://www.aepiunc.org/wp-content/uploads/216732_10151423906737615_770169408_n.jpg", :description => "It has many names, perhaps the most illustrious being \"Frat Mecca.\" Carolina Cup is where keg stands, fried chicken, floppy hats and drunk college kids are at their best.", :date => "12/11", :time => "2:00 PM"})

Event.create({:title => "Pool Party", :venue => "Davidson College Athletic Center", :address => "Davidson College, Davidson, NC", :imgurl => "http://www.bathsbudapest.com/wp-content/uploads/2013/04/Szechenyi-Bath-Party-Budapest-Szecska-Sandor-Fegyverneky.jpg", :description => "Yeah, things are going to get wet. Clothing optional.", :date => "07/21", :time => "9:50 PM"})

Event.create({:title => "Youth Soccer Tournament", :venue => "Richardson Stadium", :address => "Davidson College, Davidson, NC", :imgurl => "http://ryanaweaver.com/files/2013/02/kids-soccer-game.jpg", :description => "The annual Davison College youth soccer torunament is back for another round. Grab a lawn chair, a cooler of beer, and get ready to watch some tykes kick a ball. Plenty of fun for the whole family.", :date => "09/15", :time => "8:00 PM"})

Event.create({:title => "Dev Bootcamp Hackathon", :venue => "Dev Bootcamp Office", :address => "633 Folsom Street, San Francisco, CA", :imgurl => "http://www.thedrum.com/uploads/drum_column_article/119859/main_images/hackathon_0.jpg", :description => "The greatest and original coding bootcamp is hosting a hackathon! Come prove your skills and drink beer with us.", :date => "07/21", :time => "8:00 AM"})